In [1]:
import pandas as pd

df = pd.read_csv('merged-dataset.csv', parse_dates=['start_date', 'end_date'])

/var/folders/pn/0bn7dksx05d8k5q8rpx3vxm80000gn/T/ipykernel_20280/325539370.py:3: DtypeWarning: Columns (12,14,15,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('merged-dataset.csv', parse_dates=['start_date', 'end_date'])
/var/folders/pn/0bn7dksx05d8k5q8rpx3vxm80000gn/T/ipykernel_20280/325539370.py:3: UserWarning: Parsing dates in %d.%m.%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df = pd.read_csv('merged-dataset.csv', parse_dates=['start_date', 'end_date'])
/var/folders/pn/0bn7dksx05d8k5q8rpx3vxm80000gn/T/ipykernel_20280/325539370.py:3: UserWarning: Parsing dates in %d.%m.%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df = pd.read_csv('merged-dataset.csv', parse_dates=['start_date', 'end_date'])

In [2]:
df = df.drop(columns=['Unnamed: 0'])

In [3]:
df.columns

Index(['season', 'field', 'work_type', 'work_subtype', 'start_date',
       'end_date', 'completed_work_area', 'main_tech', 'add_tech', 'mech',
       'proc_depth', 'prod_purpose', 'prod_weight', 'prod_dry_perc',
       'prod_humid', 'prod_impur', 'yield_fact', 'work_id', 'region',
       'land_type', 'fertility_score', 'crop', 'crop_predecessor',
       'crop_yearold', 'field_area', 'hybrid', 'reproduction', 'seed_origin',
       'technology', 'yield_plan', 'p2o5', 'k2o', 'humus', 'ph',
       'inv_item_type', 'inv_item_name', 'inv_item_weight', 'inv_item_unit',
       'inv_item_dose', 'inv_item_date'],
      dtype='object')

In [4]:
df.head()

,season,field,work_type,work_subtype,start_date,end_date,completed_work_area,main_tech,add_tech,mech,...,p2o5,k2o,humus,ph,inv_item_type,inv_item_name,inv_item_weight,inv_item_unit,inv_item_dose,inv_item_date
0,2023,16.13.12.044.00,Обработка почвы,Боронование,2022-04-29,2022-04-30,"49,78","Трактор колесный Fendt 936 Vario, гос.ном. 050...",Арендованная техника,Ахметсафин Айрат Рафикович,...,"217,43","211,57","6,60","6,20",NaN,NaN,NaN,NaN,NaN,NaN
1,2023,16.13.12.017.00,Обработка почвы,Боронование,2022-05-01,2022-05-02,"154,76","Трактор колесный Птз К-744Р4, гос.ном. 2251АА1...","Борона зубовая Veles АГС-22-2У.М, зав.ном. 789",Ямалетдинов Фарид Расыхович,...,"232,65","216,06","8,80","6,75",NaN,NaN,NaN,NaN,NaN,NaN
2,2023,16.13.12.012.00,Обработка почвы,Боронование,2022-05-02,2022-05-03,"40,62","Трактор колесный Fendt 936 Vario, гос.ном. 050...",Арендованная техника,Мухаметзянов Ринат Айратович,...,"247,50","216,33","8,58","7,33",NaN,NaN,NaN,NaN,NaN,NaN
3,2023,16.13.12.012.00,Обработка почвы,Боронование,2022-05-02,2022-05-03,"86,00","Трактор колесный Птз К-744Р4, гос.ном. 2251АА1...","Борона зубовая Veles АГС-22-2У.М, зав.ном. 789",Шакиров Ринат Галиевич,...,"247,50","216,33","8,58","7,33",NaN,NaN,NaN,NaN,NaN,NaN
4,2023,16.13.12.017.00,Обработка почвы,Боронование,2022-05-02,2022-05-03,"76,00","Трактор колесный Птз К-744Р4, гос.ном. 2251АА1...","Борона зубовая Veles АГС-22-2У.М, зав.ном. 789",Шакиров Ринат Галиевич,...,"232,65","216,06","8,80","6,75",NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.sort_values(by='start_date', ascending=True).reset_index()

,index,season,field,work_type,work_subtype,start_date,end_date,completed_work_area,main_tech,add_tech,...,p2o5,k2o,humus,ph,inv_item_type,inv_item_name,inv_item_weight,inv_item_unit,inv_item_dose,inv_item_date
0,0,2023,16.13.12.044.00,Обработка почвы,Боронование,2022-04-29,2022-04-30,"49,78","Трактор колесный Fendt 936 Vario, гос.ном. 050...",Арендованная техника,...,"217,43","211,57","6,60","6,20",NaN,NaN,NaN,NaN,NaN,NaN
1,1,2023,16.13.12.017.00,Обработка почвы,Боронование,2022-05-01,2022-05-02,"154,76","Трактор колесный Птз К-744Р4, гос.ном. 2251АА1...","Борона зубовая Veles АГС-22-2У.М, зав.ном. 789",...,"232,65","216,06","8,80","6,75",NaN,NaN,NaN,NaN,NaN,NaN
2,2,2023,16.13.12.012.00,Обработка почвы,Боронование,2022-05-02,2022-05-03,"40,62","Трактор колесный Fendt 936 Vario, гос.ном. 050...",Арендованная техника,...,"247,50","216,33","8,58","7,33",NaN,NaN,NaN,NaN,NaN,NaN
3,3,2023,16.13.12.012.00,Обработка почвы,Боронование,2022-05-02,2022-05-03,"86,00","Трактор колесный Птз К-744Р4, гос.ном. 2251АА1...","Борона зубовая Veles АГС-22-2У.М, зав.ном. 789",...,"247,50","216,33","8,58","7,33",NaN,NaN,NaN,NaN,NaN,NaN
4,4,2023,16.13.12.017.00,Обработка почвы,Боронование,2022-05-02,2022-05-03,"76,00","Трактор колесный Птз К-744Р4, гос.ном. 2251АА1...","Борона зубовая Veles АГС-22-2У.М, зав.ном. 789",...,"232,65","216,06","8,80","6,75",NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228631,228616,2024,54.28.07.028.00,Обработка почвы,Культивация,2024-10-27,2024-10-28,"64,00","Трактор колесный John Deere 9470R, гос.ном. 48...","Культиватор стерневой Vaderstad TopDown 700, и...",...,"0,00","0,00","0,00","0,00",NaN,NaN,NaN,NaN,NaN,NaN
228632,228624,2024,40.04.07.010.00,Уборка,Уборка силос/карнаж,2024-10-27,2024-10-27,"27,00","Комбайн кормоуборочный John Deere 8400, гос.но...","Жатка кукурузная John Deere 375 Plus, инв.ном....",...,"5,28","265,10","34,72","1,54",NaN,NaN,NaN,NaN,NaN,NaN
228633,228634,2024,54.28.07.028.00,Обработка почвы,Культивация,2024-10-28,2024-10-28,"6,00","Трактор колесный John Deere 9470R, гос.ном. 48...","Культиватор стерневой Vaderstad TopDown 700, и...",...,"0,00","0,00","0,00","0,00",NaN,NaN,NaN,NaN,NaN,NaN
228634,228633,2024,54.28.07.028.00,Обработка почвы,Культивация,2024-10-28,2024-10-28,"3,14","Трактор колесный John Deere 8370R, гос.ном. 49...","Культиватор стерневой Vaderstad TopDown 500, з...",...,"0,00","0,00","0,00","0,00",NaN,NaN,NaN,NaN,NaN,NaN
228635,228635,2024,54.17.02.022.00,Уборка,Вывоз,2024-10-28,2024-10-28,"73,93","Трактор колесный Птз К-744Р1, гос.ном. 2206НМ7...",NaN,...,"5,69","170,67","221,63","4,81",NaN,NaN,NaN,NaN,NaN,NaN