In [78]:
import pandas as pd

fields = pd.read_csv('ekoniva-dataset/fields.csv', encoding='utf-8')
value = pd.read_csv('ekoniva-dataset/value.csv', encoding='utf-8')
works = pd.read_csv('ekoniva-dataset/works.csv', encoding='utf-8', parse_dates=['start_date', 'end_date'], dayfirst=True)

In [79]:
fields.head()

,field,region,land_type,fertility_score,season,crop,crop_predecessor,crop_yearold,area,hybrid,reproduction,seed_origin,technology,yield_plan,p2o5,k2o,humus,ph
0,22.47.01.001.01,Алтай,пашня,NaN,2023,Оз.пшеница мягкая,Пар; Яр.пшеница мягкая,NaN,"306,22",Скипетр,ЭС,Покупные,минимальная,"3,80","243,16","226,93","4,46","5,78"
1,22.47.01.001.02,Алтай,пашня,NaN,2023,Пар,Пар; Яр.пшеница мягкая,NaN,"63,16",NaN,NaN,NaN,минимальная,NaN,"243,16","226,93","4,46","5,78"
2,22.47.01.002.00,Алтай,пашня,4.0,2023,Пар,Яр.пшеница мягкая,NaN,"485,79",NaN,NaN,NaN,NaN,NaN,"219,78","204,60","3,85","5,72"
3,22.47.01.003.00,Алтай,пашня,4.0,2023,Оз.пшеница мягкая,Пар,NaN,"452,25",Скипетр,ЭС,Покупные,минимальная,"3,80","205,15","192,28","6,49","5,94"
4,22.47.01.004.00,Алтай,пашня,3.0,2023,Оз.пшеница мягкая,Пар,NaN,"269,64",Скипетр,ЭС,Покупные,минимальная,"3,80","183,26","162,69","6,16","5,94"

In [80]:
fields['land_type'].value_counts()

land_type
пашня                    15636
луг                        291
пастбище естественное      127
Name: count, dtype: int64

In [81]:
fields['region'].value_counts()

region
Калуга         4694
Воронеж        4037
Рязань         1963
Новосибирск    1250
Курск           934
Татарстан       805
Оренбург        524
Москва          504
Башкирия        481
Алтай           254
Самара          241
Тюмень          218
СПб             149
Name: count, dtype: int64

In [82]:
fields['season'].value_counts()

season
2024    8145
2023    7909
Name: count, dtype: int64

In [83]:
counts = fields['crop'].value_counts().reset_index()
counts.columns = ['crop', 'count']
counts[counts['count'] > 100]

                         crop  count
0                 Залежь, лес   2760
1              Кукуруза силос   1682
2         Люцерна пр.лет корм   1207
3                         Пар   1115
4           Оз.пшеница мягкая    969
5              Кукуруза зерно    808
6                         Соя    799
7           Яр.пшеница мягкая    783
8          Люцерна 1 г.ж.корм    539
9                   Яр.ячмень    519
10               Подсолнечник    413
11                     Залежь    382
12                        Луг    297
13     Эсп.+костр.пр.лет корм    248
14          Пастбище на пашне    227
15     Кл.кр.+тим.пр.лет корм    208
16                   Чечевица    180
17                 Сах.свекла    177
18            Кукуруза корнаж    163
19           Чечевица зеленая    162
20                      Горох    147
21      Пастбище естественное    137
22          Залежь, кустарник    131
23  Одн.тр.суданская тр.корм.    129
24              Лён масличный    110

In [84]:
counts = fields['crop_predecessor'].value_counts().reset_index()
counts.columns = ['crop_predecessor', 'count']
counts[counts['count'] > 100]

          crop_predecessor  count
0              Залежь, лес   2725
1           Кукуруза силос   1748
2      Люцерна пр.лет корм   1298
3        Оз.пшеница мягкая   1130
4        Яр.пшеница мягкая    902
5                      Пар    783
6                      Соя    756
7           Кукуруза зерно    741
8                Яр.ячмень    513
9       Люцерна 1 г.ж.корм    462
10                  Залежь    333
11            Подсолнечник    308
12           Лён масличный    297
13                     Луг    291
14  Эсп.+костр.пр.лет корм    273
15                Чечевица    250
16       Пастбище на пашне    245
17                   Горох    177
18         Кукуруза корнаж    169
19              Сах.свекла    147
20       Залежь, кустарник    141
21   Пастбище естественное    140
22  Кл.кр.+тим.пр.лет корм    113

In [85]:
counts = fields['hybrid'].value_counts().reset_index()
counts.columns = ['hybrid', 'count']
counts[counts['count'] > 100]

            hybrid  count
0     Смесь сортов    531
1         Ликамеро    420
2          Скипетр    304
3         БН 06-18    291
4         Галифакс    258
5           Дакота    248
6            Сарга    242
7          Аргента    186
8       Каскад 166    175
9    Песчаный 1251    173
10          Рэдкот    164
11          Кермит    155
12         Маргрет    154
13        Талисман    146
14           Верко    135
15           Микси    115
16  Кинельская 100    112
17     Росс 140 СВ    112
18     ОАК Пруденс    107
19     Льговская 4    106
20          Планет    102

In [86]:
fields['reproduction'].value_counts()

reproduction
F1                   2413
РС-1                 2097
ЭС                   1048
РС-2                  959
РСт                   743
Смесь репродукций     327
РС-3                  307
СЭ                    158
ПР-2                   36
ОС                     36
ПР-1                   35
Без репродукции        33
ПР                      1
Name: count, dtype: int64

In [87]:
fields['seed_origin'].value_counts()

seed_origin
Покупные           5124
Свои               3240
Свои + покупные     103
Name: count, dtype: int64

In [88]:
fields['technology'].value_counts()

technology
минимальная                 4793
классическая с плугом       2936
нулевая с прямым посевом     998
гибридизация                  38
Name: count, dtype: int64

In [89]:
value.head()

,field,inv_item_type,inv_item_name,inv_item_weight,inv_item_unit,inv_item_dose,inv_item_date,work_id
0,36.01.21.025.01,Удобрения,Удобрение 31,"15017,60",кг,"260,00",28.10.2024,E3A7DAEB-D124-4685-ADE1-199818C77361
1,36.14.12.064.00,Удобрения,Удобрение 31,"6500,00",м3,"65,00",28.10.2024,0AB8C8D7-04BD-4483-98B2-3E062CDD7E3E
2,36.14.16.008.00,Удобрения,Удобрение 49,"7865,00",т,"65,00",28.10.2024,00E51F81-0A4F-4983-B068-877A089FFD33
3,36.14.16.008.00,Удобрения,Удобрение 49,"10985,00",т,"65,00",28.10.2024,150F0150-8061-4CE9-9570-B112CBAD7C51
4,36.14.16.008.00,Удобрения,Удобрение 49,"10985,00",т,"65,00",28.10.2024,D5D1EADB-D159-4CF8-8C2A-171517ACD403

In [90]:
value['inv_item_type'].value_counts()

inv_item_type
СЗР          100115
Удобрения     43008
Семена        27690
Name: count, dtype: int64

In [91]:
works.head()

,season,field,work_type,work_subtype,start_date,end_date,area,main_tech,add_tech,mech,proc_depth,prod_purpose,prod_weight,prod_dry_perc,prod_humid,prod_impur,yield_fact,work_id
0,2023,16.13.12.044.00,Обработка почвы,Боронование,2022-04-29,2022-04-30,"49,78","Трактор колесный Fendt 936 Vario, гос.ном. 050...",Арендованная техника,Ахметсафин Айрат Рафикович,"10,00",NaN,"0,00",NaN,NaN,NaN,"0,00",A06AD38A-5448-40EC-B095-4B8918B4AC10
1,2023,16.13.12.017.00,Обработка почвы,Боронование,2022-05-01,2022-05-02,"154,76","Трактор колесный Птз К-744Р4, гос.ном. 2251АА1...","Борона зубовая Veles АГС-22-2У.М, зав.ном. 789",Ямалетдинов Фарид Расыхович,"10,00",NaN,"0,00",NaN,NaN,NaN,"0,00",62B13DCE-FFB5-4E7A-8F1B-88930BD338EF
2,2023,16.13.12.012.00,Обработка почвы,Боронование,2022-05-02,2022-05-03,"40,62","Трактор колесный Fendt 936 Vario, гос.ном. 050...",Арендованная техника,Мухаметзянов Ринат Айратович,"10,00",NaN,"0,00",NaN,NaN,NaN,"0,00",D5884A6D-4710-4C0A-8E5A-878291B89846
3,2023,16.13.12.012.00,Обработка почвы,Боронование,2022-05-02,2022-05-03,"86,00","Трактор колесный Птз К-744Р4, гос.ном. 2251АА1...","Борона зубовая Veles АГС-22-2У.М, зав.ном. 789",Шакиров Ринат Галиевич,"10,00",NaN,"0,00",NaN,NaN,NaN,"0,00",7A504837-1127-4315-ACF1-171AC80111BF
4,2023,16.13.12.017.00,Обработка почвы,Боронование,2022-05-02,2022-05-03,"76,00","Трактор колесный Птз К-744Р4, гос.ном. 2251АА1...","Борона зубовая Veles АГС-22-2У.М, зав.ном. 789",Шакиров Ринат Галиевич,"10,00",NaN,"0,00",NaN,NaN,NaN,"0,00",7FE86DA8-614B-4EBE-85CB-6AF80C08689F

In [92]:
works['mech'].shape[0]

174683

In [93]:
works['mech'].unique().shape[0]

1536

In [94]:
works['work_type'].value_counts()

work_type
Уборка                59097
Обработка почвы       54129
Внесение СЗР          26460
Сев                   18081
Внесение удобрений    16916
Name: count, dtype: int64

In [95]:
works['work_subtype'].value_counts()

work_subtype
Обработка СЗР                             23790
Прямое комбайнирование                    23371
Культивация                               14490
Дискование                                14082
Внесение минеральных удобрений            13326
Сев без внесения удобрений                10240
Вспашка                                    9805
Кошение                                    8185
Сев с внесением удобрений                  7841
Вывоз                                      7520
Боронование                                7482
Прикатывание                               5677
Уборка силос/карнаж                        5577
Подбор (корм)                              5395
Сгребание в валки                          3879
Внесение СЗР и удобрений                   2629
Прессование                                2483
Внесение органических удобрений            2331
Глубокорыхление                            1453
Внесение жидких органических удобрений     1259
Мульчирование                               858
Подбор и обмолот                            791
Подбор                                      618
Копка                                       495
Ворошение                                   376
Вывоз (тех.культуры)                        306
Междурядная обработка без внесения          242
Заготовка сенажа                             98
Дератизация                                  41
Уборка камней                                40
Уборка трав                                   3
Name: count, dtype: int64

In [96]:
works['start_month'] = works['start_date'].dt.month
works['end_month'] = works['end_date'].dt.month
works['delta'] = works['end_date'] - works['start_date']
works['delta'].value_counts()[:30]

delta
0 days     133493
1 days      25607
2 days       2715
3 days       1017
4 days        581
5 days        375
7 days        235
6 days        212
8 days        171
9 days        126
31 days       114
10 days        95
14 days        69
11 days        65
15 days        60
13 days        56
30 days        56
12 days        52
16 days        37
32 days        33
17 days        28
18 days        27
33 days        26
27 days        25
19 days        23
34 days        22
22 days        21
23 days        20
20 days        18
61 days        14
Name: count, dtype: int64

In [97]:
worker = works[works['mech'] == works['mech'][0]][['work_type', 'work_subtype', 'season', 'start_month', 'end_month']].reset_index()

In [98]:
movements = worker[worker['season'] == 2023].sort_values(by='start_month')[['work_type', 'work_subtype']]

In [99]:
for i in range(movements.shape[0]):
    print(movements['work_type'][i], movements['work_subtype'][i])

Обработка почвы Боронование
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Вспашка
Обработка почвы Вспашка
Обработка почвы Вспашка
Обработка почвы Вспашка
Обработка почвы Вспашка
Обработка почвы Вспашка
Обработка почвы Вспашка
Обработка почвы Вспашка
Обработка почвы Вспашка
Обработка почвы Вспашка
Обработка почвы Вспашка
Обработка почвы Вспашка
Обработка почвы Вспашка
Обработка почвы Вспашка
Обработка почвы Вспашка
Обработка почвы Вспашка
Обработка почвы Вспашка
Обработка почвы Вспашка
Обработка почвы Вспашка
Обработка почвы Вспашка
Обработка почвы Вспашка
Обработка почвы Вспашка
Обработка почвы Вспашка
Обработка почвы Вспашка
Обработка почвы Вспашка
Обработка почвы Вспашка
Обработка почвы Культивация
Обработка почвы Культивация
Обработка почвы Культивация
Обработка почвы Глубокорыхление
Обработка почвы Прикатывание
Обработка почвы Боронование
Обработка почвы Боронование
Обработка почвы Боронование
Обработка почвы Боронование
Обработка почвы Боронование
Обработка почвы Боронование
Обработка почвы Боронование
Обработка почвы Боронование
Обработка почвы Боронование
Обработка почвы Боронование
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание
Обработка почвы Прикатывание

In [100]:
works = works.groupby('mech')['work_type'].apply(lambda x: ','.join(set(list(x))))
works

mech
Admin MS SQL                                                                    Уборка
Абабков Данил Павлович                                                    Внесение СЗР
Абдулов Руслан Флюрович              Уборка,Внесение удобрений,Сев,Внесение СЗР,Обр...
Абдураззоков Ифтихор Боиржонович             Обработка почвы,Внесение удобрений,Уборка
Абдурахманов Абдурахман Шарипович                                               Уборка
                                                           ...
Якушин Иван Владимирович                                                        Уборка
Яланжи Александр Николаевич                                            Обработка почвы
Ямалетдинов Фарид Расыхович                                     Обработка почвы,Уборка
Яныкин Алексей Михайлович                                   Обработка почвы,Сев,Уборка
Яркин Михаил Владимирович                      Обработка почвы,Внесение СЗР,Сев,Уборка
Name: work_type, Length: 1536, dtype: object

In [105]:
crops = fields[fields['land_type'] == 'пастбище естественное'][['crop', 'crop_predecessor']]

In [106]:
crops['crop'].value_counts()

crop
Пастбище естественное    123
Залежь, кустарник          2
Кукуруза силос             1
Залежь                     1
Name: count, dtype: int64