In [1]:
import pandas as pd

In [2]:
works = pd.read_csv('ekoniva-dataset/works.csv')
fields = pd.read_csv('ekoniva-dataset/fields.csv')
value = pd.read_csv('ekoniva-dataset/value.csv', parse_dates=['inv_item_date'], dayfirst=True)

In [3]:
works.head()

,season,field,work_type,work_subtype,start_date,end_date,area,main_tech,add_tech,mech,proc_depth,prod_purpose,prod_weight,prod_dry_perc,prod_humid,prod_impur,yield_fact,work_id
0,2023,16.13.12.044.00,Обработка почвы,Боронование,29.04.2022,30.04.2022,"49,78","Трактор колесный Fendt 936 Vario, гос.ном. 050...",Арендованная техника,Ахметсафин Айрат Рафикович,"10,00",NaN,"0,00",NaN,NaN,NaN,"0,00",A06AD38A-5448-40EC-B095-4B8918B4AC10
1,2023,16.13.12.017.00,Обработка почвы,Боронование,01.05.2022,02.05.2022,"154,76","Трактор колесный Птз К-744Р4, гос.ном. 2251АА1...","Борона зубовая Veles АГС-22-2У.М, зав.ном. 789",Ямалетдинов Фарид Расыхович,"10,00",NaN,"0,00",NaN,NaN,NaN,"0,00",62B13DCE-FFB5-4E7A-8F1B-88930BD338EF
2,2023,16.13.12.012.00,Обработка почвы,Боронование,02.05.2022,03.05.2022,"40,62","Трактор колесный Fendt 936 Vario, гос.ном. 050...",Арендованная техника,Мухаметзянов Ринат Айратович,"10,00",NaN,"0,00",NaN,NaN,NaN,"0,00",D5884A6D-4710-4C0A-8E5A-878291B89846
3,2023,16.13.12.012.00,Обработка почвы,Боронование,02.05.2022,03.05.2022,"86,00","Трактор колесный Птз К-744Р4, гос.ном. 2251АА1...","Борона зубовая Veles АГС-22-2У.М, зав.ном. 789",Шакиров Ринат Галиевич,"10,00",NaN,"0,00",NaN,NaN,NaN,"0,00",7A504837-1127-4315-ACF1-171AC80111BF
4,2023,16.13.12.017.00,Обработка почвы,Боронование,02.05.2022,03.05.2022,"76,00","Трактор колесный Птз К-744Р4, гос.ном. 2251АА1...","Борона зубовая Veles АГС-22-2У.М, зав.ном. 789",Шакиров Ринат Галиевич,"10,00",NaN,"0,00",NaN,NaN,NaN,"0,00",7FE86DA8-614B-4EBE-85CB-6AF80C08689F

In [4]:
fields.head()

,field,region,land_type,fertility_score,season,crop,crop_predecessor,crop_yearold,area,hybrid,reproduction,seed_origin,technology,yield_plan,p2o5,k2o,humus,ph
0,22.47.01.001.01,Алтай,пашня,NaN,2023,Оз.пшеница мягкая,Пар; Яр.пшеница мягкая,NaN,"306,22",Скипетр,ЭС,Покупные,минимальная,"3,80","243,16","226,93","4,46","5,78"
1,22.47.01.001.02,Алтай,пашня,NaN,2023,Пар,Пар; Яр.пшеница мягкая,NaN,"63,16",NaN,NaN,NaN,минимальная,NaN,"243,16","226,93","4,46","5,78"
2,22.47.01.002.00,Алтай,пашня,4.0,2023,Пар,Яр.пшеница мягкая,NaN,"485,79",NaN,NaN,NaN,NaN,NaN,"219,78","204,60","3,85","5,72"
3,22.47.01.003.00,Алтай,пашня,4.0,2023,Оз.пшеница мягкая,Пар,NaN,"452,25",Скипетр,ЭС,Покупные,минимальная,"3,80","205,15","192,28","6,49","5,94"
4,22.47.01.004.00,Алтай,пашня,3.0,2023,Оз.пшеница мягкая,Пар,NaN,"269,64",Скипетр,ЭС,Покупные,минимальная,"3,80","183,26","162,69","6,16","5,94"

In [5]:
value.head()

,field,inv_item_type,inv_item_name,inv_item_weight,inv_item_unit,inv_item_dose,inv_item_date,work_id
0,36.01.21.025.01,Удобрения,Удобрение 31,"15017,60",кг,"260,00",2024-10-28,E3A7DAEB-D124-4685-ADE1-199818C77361
1,36.14.12.064.00,Удобрения,Удобрение 31,"6500,00",м3,"65,00",2024-10-28,0AB8C8D7-04BD-4483-98B2-3E062CDD7E3E
2,36.14.16.008.00,Удобрения,Удобрение 49,"7865,00",т,"65,00",2024-10-28,00E51F81-0A4F-4983-B068-877A089FFD33
3,36.14.16.008.00,Удобрения,Удобрение 49,"10985,00",т,"65,00",2024-10-28,150F0150-8061-4CE9-9570-B112CBAD7C51
4,36.14.16.008.00,Удобрения,Удобрение 49,"10985,00",т,"65,00",2024-10-28,D5D1EADB-D159-4CF8-8C2A-171517ACD403

In [6]:
df_intermediate = works.merge(fields, 'left', on=['field', 'season'])

In [7]:
df_intermediate.columns

Index(['season', 'field', 'work_type', 'work_subtype', 'start_date',
       'end_date', 'area_x', 'main_tech', 'add_tech', 'mech', 'proc_depth',
       'prod_purpose', 'prod_weight', 'prod_dry_perc', 'prod_humid',
       'prod_impur', 'yield_fact', 'work_id', 'region', 'land_type',
       'fertility_score', 'crop', 'crop_predecessor', 'crop_yearold', 'area_y',
       'hybrid', 'reproduction', 'seed_origin', 'technology', 'yield_plan',
       'p2o5', 'k2o', 'humus', 'ph'],
      dtype='object')

In [8]:
df = df_intermediate.merge(value, "left", on=["field", "work_id"])

In [9]:
df

,season,field,work_type,work_subtype,start_date,end_date,area_x,main_tech,add_tech,mech,...,p2o5,k2o,humus,ph,inv_item_type,inv_item_name,inv_item_weight,inv_item_unit,inv_item_dose,inv_item_date
0,2023,16.13.12.044.00,Обработка почвы,Боронование,29.04.2022,30.04.2022,"49,78","Трактор колесный Fendt 936 Vario, гос.ном. 050...",Арендованная техника,Ахметсафин Айрат Рафикович,...,"217,43","211,57","6,60","6,20",NaN,NaN,NaN,NaN,NaN,NaT
1,2023,16.13.12.017.00,Обработка почвы,Боронование,01.05.2022,02.05.2022,"154,76","Трактор колесный Птз К-744Р4, гос.ном. 2251АА1...","Борона зубовая Veles АГС-22-2У.М, зав.ном. 789",Ямалетдинов Фарид Расыхович,...,"232,65","216,06","8,80","6,75",NaN,NaN,NaN,NaN,NaN,NaT
2,2023,16.13.12.012.00,Обработка почвы,Боронование,02.05.2022,03.05.2022,"40,62","Трактор колесный Fendt 936 Vario, гос.ном. 050...",Арендованная техника,Мухаметзянов Ринат Айратович,...,"247,50","216,33","8,58","7,33",NaN,NaN,NaN,NaN,NaN,NaT
3,2023,16.13.12.012.00,Обработка почвы,Боронование,02.05.2022,03.05.2022,"86,00","Трактор колесный Птз К-744Р4, гос.ном. 2251АА1...","Борона зубовая Veles АГС-22-2У.М, зав.ном. 789",Шакиров Ринат Галиевич,...,"247,50","216,33","8,58","7,33",NaN,NaN,NaN,NaN,NaN,NaT
4,2023,16.13.12.017.00,Обработка почвы,Боронование,02.05.2022,03.05.2022,"76,00","Трактор колесный Птз К-744Р4, гос.ном. 2251АА1...","Борона зубовая Veles АГС-22-2У.М, зав.ном. 789",Шакиров Ринат Галиевич,...,"232,65","216,06","8,80","6,75",NaN,NaN,NaN,NaN,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219492,2024,54.17.12.029.00,Уборка,Подбор (корм),27.10.2024,27.10.2024,"27,00","Комбайн кормоуборочный Ростсельмаш F2650, гос....",NaN,Ульвачев Алексей Николаевич,...,"5,06","241,12","184,23","8,03",NaN,NaN,NaN,NaN,NaN,NaT
219493,2024,54.28.13.038.00,Уборка,Вывоз,27.10.2024,27.10.2024,"7,00","Трактор колесный Lovol 2604, зав.ном. M700060R...",Арендованная техника,Лагунов Юрий Николаевич,...,"5,72","216,26","347,81","6,27",NaN,NaN,NaN,NaN,NaN,NaT
219494,2024,54.28.07.028.00,Обработка почвы,Культивация,28.10.2024,28.10.2024,"3,14","Трактор колесный John Deere 8370R, гос.ном. 49...","Культиватор стерневой Vaderstad TopDown 500, з...",Гопаненко Владимир Владимирович,...,"0,00","0,00","0,00","0,00",NaN,NaN,NaN,NaN,NaN,NaT
219495,2024,54.28.07.028.00,Обработка почвы,Культивация,28.10.2024,28.10.2024,"6,00","Трактор колесный John Deere 9470R, гос.ном. 48...","Культиватор стерневой Vaderstad TopDown 700, и...",Гамануха Дмитрий Владимирович,...,"0,00","0,00","0,00","0,00",NaN,NaN,NaN,NaN,NaN,NaT
219496,2024,54.17.02.022.00,Уборка,Вывоз,28.10.2024,28.10.2024,"73,93","Трактор колесный Птз К-744Р1, гос.ном. 2206НМ7...",NaN,Строй Дмитрий Александрович,...,"5,69","170,67","221,63","4,81",NaN,NaN,NaN,NaN,NaN,NaT