In [1]:
import pandas as pd

In [2]:
works = pd.read_csv('ekoniva-dataset/works.csv')
fields = pd.read_csv('ekoniva-dataset/fields.csv')
value = pd.read_csv('ekoniva-dataset/value.csv', parse_dates=['inv_item_date'], dayfirst=True)

In [3]:
works.head()

,season,field,work_type,work_subtype,start_date,end_date,area,main_tech,add_tech,mech,proc_depth,prod_purpose,prod_weight,prod_dry_perc,prod_humid,prod_impur,yield_fact,work_id
0,2023,16.13.12.044.00,Обработка почвы,Боронование,29.04.2022,30.04.2022,"49,78","Трактор колесный Fendt 936 Vario, гос.ном. 050...",Арендованная техника,Ахметсафин Айрат Рафикович,"10,00",NaN,"0,00",NaN,NaN,NaN,"0,00",A06AD38A-5448-40EC-B095-4B8918B4AC10
1,2023,16.13.12.017.00,Обработка почвы,Боронование,01.05.2022,02.05.2022,"154,76","Трактор колесный Птз К-744Р4, гос.ном. 2251АА1...","Борона зубовая Veles АГС-22-2У.М, зав.ном. 789",Ямалетдинов Фарид Расыхович,"10,00",NaN,"0,00",NaN,NaN,NaN,"0,00",62B13DCE-FFB5-4E7A-8F1B-88930BD338EF
2,2023,16.13.12.012.00,Обработка почвы,Боронование,02.05.2022,03.05.2022,"40,62","Трактор колесный Fendt 936 Vario, гос.ном. 050...",Арендованная техника,Мухаметзянов Ринат Айратович,"10,00",NaN,"0,00",NaN,NaN,NaN,"0,00",D5884A6D-4710-4C0A-8E5A-878291B89846
3,2023,16.13.12.012.00,Обработка почвы,Боронование,02.05.2022,03.05.2022,"86,00","Трактор колесный Птз К-744Р4, гос.ном. 2251АА1...","Борона зубовая Veles АГС-22-2У.М, зав.ном. 789",Шакиров Ринат Галиевич,"10,00",NaN,"0,00",NaN,NaN,NaN,"0,00",7A504837-1127-4315-ACF1-171AC80111BF
4,2023,16.13.12.017.00,Обработка почвы,Боронование,02.05.2022,03.05.2022,"76,00","Трактор колесный Птз К-744Р4, гос.ном. 2251АА1...","Борона зубовая Veles АГС-22-2У.М, зав.ном. 789",Шакиров Ринат Галиевич,"10,00",NaN,"0,00",NaN,NaN,NaN,"0,00",7FE86DA8-614B-4EBE-85CB-6AF80C08689F

In [4]:
fields.head()

,field,region,land_type,fertility_score,season,crop,crop_predecessor,crop_yearold,area,hybrid,reproduction,seed_origin,technology,yield_plan,p2o5,k2o,humus,ph
0,22.47.01.001.01,Алтай,пашня,NaN,2023,Оз.пшеница мягкая,Пар; Яр.пшеница мягкая,NaN,"306,22",Скипетр,ЭС,Покупные,минимальная,"3,80","243,16","226,93","4,46","5,78"
1,22.47.01.001.02,Алтай,пашня,NaN,2023,Пар,Пар; Яр.пшеница мягкая,NaN,"63,16",NaN,NaN,NaN,минимальная,NaN,"243,16","226,93","4,46","5,78"
2,22.47.01.002.00,Алтай,пашня,4.0,2023,Пар,Яр.пшеница мягкая,NaN,"485,79",NaN,NaN,NaN,NaN,NaN,"219,78","204,60","3,85","5,72"
3,22.47.01.003.00,Алтай,пашня,4.0,2023,Оз.пшеница мягкая,Пар,NaN,"452,25",Скипетр,ЭС,Покупные,минимальная,"3,80","205,15","192,28","6,49","5,94"
4,22.47.01.004.00,Алтай,пашня,3.0,2023,Оз.пшеница мягкая,Пар,NaN,"269,64",Скипетр,ЭС,Покупные,минимальная,"3,80","183,26","162,69","6,16","5,94"

In [5]:
value.head()

,field,inv_item_type,inv_item_name,inv_item_weight,inv_item_unit,inv_item_dose,inv_item_date,work_id
0,36.01.21.025.01,Удобрения,Удобрение 31,"15017,60",кг,"260,00",2024-10-28,E3A7DAEB-D124-4685-ADE1-199818C77361
1,36.14.12.064.00,Удобрения,Удобрение 31,"6500,00",м3,"65,00",2024-10-28,0AB8C8D7-04BD-4483-98B2-3E062CDD7E3E
2,36.14.16.008.00,Удобрения,Удобрение 49,"7865,00",т,"65,00",2024-10-28,00E51F81-0A4F-4983-B068-877A089FFD33
3,36.14.16.008.00,Удобрения,Удобрение 49,"10985,00",т,"65,00",2024-10-28,150F0150-8061-4CE9-9570-B112CBAD7C51
4,36.14.16.008.00,Удобрения,Удобрение 49,"10985,00",т,"65,00",2024-10-28,D5D1EADB-D159-4CF8-8C2A-171517ACD403

In [6]:
df_intermediate = works.merge(fields, 'inner', on=['field', 'season'])

In [7]:
df_intermediate.columns

Index(['season', 'field', 'work_type', 'work_subtype', 'start_date',
       'end_date', 'area_x', 'main_tech', 'add_tech', 'mech', 'proc_depth',
       'prod_purpose', 'prod_weight', 'prod_dry_perc', 'prod_humid',
       'prod_impur', 'yield_fact', 'work_id', 'region', 'land_type',
       'fertility_score', 'crop', 'crop_predecessor', 'crop_yearold', 'area_y',
       'hybrid', 'reproduction', 'seed_origin', 'technology', 'yield_plan',
       'p2o5', 'k2o', 'humus', 'ph'],
      dtype='object')

In [8]:
df = df_intermediate.merge(value, "outer", on=["field", "work_id"])

In [9]:
df

,season,field,work_type,work_subtype,start_date,end_date,area_x,main_tech,add_tech,mech,...,p2o5,k2o,humus,ph,inv_item_type,inv_item_name,inv_item_weight,inv_item_unit,inv_item_dose,inv_item_date
0,2023.0,02.09.02.002.01,Обработка почвы,Культивация,27.04.2023,NaN,"58,25","Трактор колесный Ростсельмаш 2400, зав.ном. R0...","Культиватор предпосевной John Deere 2210, зав....",Асмандияров Вячеслав Владимирович,...,"0,00","0,00","0,00","0,00",NaN,NaN,NaN,NaN,NaN,NaT
1,2023.0,02.09.02.002.01,Сев,Сев без внесения удобрений,28.04.2023,NaN,"90,25","Трактор колесный Fendt 936 Vario, гос.ном. 568...","Сеялка пропашная John Deere DB 55, зав.ном. 1L...",Петров Петр Александрович,...,"0,00","0,00","0,00","0,00",Семена,Гибрид Подсолнечника Фаусто F1 Express,"15883,46",п. ед.,"175,99",2023-04-28
2,2024.0,02.09.02.002.01,Уборка,Подбор (корм),02.09.2024,NaN,"32,25","Комбайн кормоуборочный John Deere 8500i, гос.н...",NaN,Миннуллин Айбулат Шамилевич,...,"0,00","0,00","0,00","0,00",NaN,NaN,NaN,NaN,NaN,NaT
3,2023.0,02.09.02.002.01,Обработка почвы,Глубокорыхление,04.11.2022,NaN,"20,00","Трактор колесный Ростсельмаш 2400, зав.ном. R0...","Культиватор стерневой Vaderstad TopDown 700, з...",Архипов Леонид Валерьевич,...,"0,00","0,00","0,00","0,00",NaN,NaN,NaN,NaN,NaN,NaT
4,NaN,02.09.02.002.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Семена,Семена пшеницы озимой Скипетр РС1 2023,"292500,00",кг,"9750,00",2024-09-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279373,2023.0,72.22.10.048.00,Уборка,Прямое комбайнирование,08.09.2023,08.09.2023,4,Комбайн зерноуборочный Massey Ferguson 5640 (7...,NaN,Шабалин Сергей Николаевич,...,"35,97","125,40","3,63","5,28",NaN,NaN,NaN,NaN,NaN,NaT
279374,2024.0,72.22.10.048.00,Обработка почвы,Дискование,17.06.2024,17.06.2024,7.24,"Трактор колесный Massey Ferguson 8737, гос.ном...","Борона дисковая Horsch Joker 8 RT, зав.ном. 28...",Шабалин Сергей Николаевич,...,"5,28","35,97","8,11","3,63",NaN,NaN,NaN,NaN,NaN,NaT
279375,2023.0,72.22.10.048.00,Сев,Сев без внесения удобрений,04.09.2022,04.09.2022,7.24,"Трактор колесный Fendt 936 Vario, гос.ном. 349...","Сеялка зерновая Vaderstad Rapid RDA 800, зав.н...",Антуганов Сергей Геннадьевич,...,"35,97","125,40","3,63","5,28",Семена,Семена Тритикале озимой Сирс-57 РС-1,"21942,01",кг,"3030,66",2022-09-04
279376,2024.0,72.22.10.048.00,Внесение удобрений,Внесение минеральных удобрений,19.06.2024,19.06.2024,7.24,"Трактор колесный Massey Ferguson 8690, гос.ном...",Разбрасыватель минеральных удобрений G?strower...,Кукарских Василий Александрович,...,"5,28","35,97","8,11","3,63",Удобрения,Удобрение 57,"10221,43",кг,"195,00",2024-06-19
279377,2023.0,72.22.10.048.00,Внесение удобрений,Внесение минеральных удобрений,22.05.2023,22.05.2023,7.24,"Трактор колесный Massey Ferguson 8690, гос.ном...",Разбрасыватель минеральных удобрений G?strower...,Кукарских Василий Александрович,...,"35,97","125,40","3,63","5,28",Удобрения,Удобрение 15,"73,98",т,"1,41",2023-05-22