In [1]:
import pandas as pd

df = pd.read_csv('merged-dataset.csv', parse_dates=['start_date', 'end_date', 'inv_item_date'])

/var/folders/pn/0bn7dksx05d8k5q8rpx3vxm80000gn/T/ipykernel_26122/1993625587.py:3: DtypeWarning: Columns (12,14,15,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('merged-dataset.csv', parse_dates=['start_date', 'end_date', 'inv_item_date'])
/var/folders/pn/0bn7dksx05d8k5q8rpx3vxm80000gn/T/ipykernel_26122/1993625587.py:3: UserWarning: Parsing dates in %d.%m.%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df = pd.read_csv('merged-dataset.csv', parse_dates=['start_date', 'end_date', 'inv_item_date'])
/var/folders/pn/0bn7dksx05d8k5q8rpx3vxm80000gn/T/ipykernel_26122/1993625587.py:3: UserWarning: Parsing dates in %d.%m.%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df = pd.read_csv('merged-dataset.csv', parse_dates=['start_date', 'end_date', 'inv_item_date'])

In [2]:
df = df.drop(columns=['Unnamed: 0'])

In [6]:
df['yield_fact'] = df['yield_fact'].str.replace(',', '.').astype(float)
df['fertility_score'] = pd.to_numeric(df['fertility_score'], errors='coerce')
df['season'] = pd.to_numeric(df['season'], errors='coerce')
df['completed_work_area'] = pd.to_numeric(df['completed_work_area'], errors='coerce')
df['field_area'] = pd.to_numeric(df['field_area'], errors='coerce')
df['yield_plan'] = pd.to_numeric(df['yield_plan'], errors='coerce')
df['p2o5'] = pd.to_numeric(df['p2o5'], errors='coerce')
df['k2o'] = pd.to_numeric(df['k2o'], errors='coerce')
df['humus'] = pd.to_numeric(df['humus'], errors='coerce')
df['ph'] = pd.to_numeric(df['ph'], errors='coerce')
df['inv_item_weight'] = pd.to_numeric(df['inv_item_weight'], errors='coerce')
df['inv_item_dose'] = pd.to_numeric(df['inv_item_dose'], errors='coerce')
df['proc_depth'] = pd.to_numeric(df['proc_depth'], errors='coerce')
df['prod_purpose'] = pd.to_numeric(df['prod_purpose'], errors='coerce')
df['prod_weight'] = pd.to_numeric(df['prod_weight'], errors='coerce')
df['prod_dry_perc'] = pd.to_numeric(df['prod_dry_perc'], errors='coerce')
df['prod_humid'] = pd.to_numeric(df['prod_humid'], errors='coerce')
df['prod_impur'] = pd.to_numeric(df['prod_impur'], errors='coerce')

In [7]:
df['yield_fact'].value_counts()

Series([], Name: count, dtype: int64)

In [5]:
df

,season,field,work_type,work_subtype,start_date,end_date,completed_work_area,main_tech,add_tech,mech,...,p2o5,k2o,humus,ph,inv_item_type,inv_item_name,inv_item_weight,inv_item_unit,inv_item_dose,inv_item_date
0,2023,16.13.12.044.00,Обработка почвы,Боронование,2022-04-29,2022-04-30,"49,78","Трактор колесный Fendt 936 Vario, гос.ном. 050...",Арендованная техника,Ахметсафин Айрат Рафикович,...,"217,43","211,57","6,60","6,20",NaN,NaN,NaN,NaN,NaN,NaT
1,2023,16.13.12.017.00,Обработка почвы,Боронование,2022-05-01,2022-05-02,"154,76","Трактор колесный Птз К-744Р4, гос.ном. 2251АА1...","Борона зубовая Veles АГС-22-2У.М, зав.ном. 789",Ямалетдинов Фарид Расыхович,...,"232,65","216,06","8,80","6,75",NaN,NaN,NaN,NaN,NaN,NaT
2,2023,16.13.12.012.00,Обработка почвы,Боронование,2022-05-02,2022-05-03,"40,62","Трактор колесный Fendt 936 Vario, гос.ном. 050...",Арендованная техника,Мухаметзянов Ринат Айратович,...,"247,50","216,33","8,58","7,33",NaN,NaN,NaN,NaN,NaN,NaT
3,2023,16.13.12.012.00,Обработка почвы,Боронование,2022-05-02,2022-05-03,"86,00","Трактор колесный Птз К-744Р4, гос.ном. 2251АА1...","Борона зубовая Veles АГС-22-2У.М, зав.ном. 789",Шакиров Ринат Галиевич,...,"247,50","216,33","8,58","7,33",NaN,NaN,NaN,NaN,NaN,NaT
4,2023,16.13.12.017.00,Обработка почвы,Боронование,2022-05-02,2022-05-03,"76,00","Трактор колесный Птз К-744Р4, гос.ном. 2251АА1...","Борона зубовая Veles АГС-22-2У.М, зав.ном. 789",Шакиров Ринат Галиевич,...,"232,65","216,06","8,80","6,75",NaN,NaN,NaN,NaN,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228631,2024,54.17.12.029.00,Уборка,Подбор (корм),2024-10-27,2024-10-27,"27,00","Комбайн кормоуборочный Ростсельмаш F2650, гос....",NaN,Ульвачев Алексей Николаевич,...,"5,06","241,12","184,23","8,03",NaN,NaN,NaN,NaN,NaN,NaT
228632,2024,54.28.13.038.00,Уборка,Вывоз,2024-10-27,2024-10-27,"7,00","Трактор колесный Lovol 2604, зав.ном. M700060R...",Арендованная техника,Лагунов Юрий Николаевич,...,"5,72","216,26","347,81","6,27",NaN,NaN,NaN,NaN,NaN,NaT
228633,2024,54.28.07.028.00,Обработка почвы,Культивация,2024-10-28,2024-10-28,"3,14","Трактор колесный John Deere 8370R, гос.ном. 49...","Культиватор стерневой Vaderstad TopDown 500, з...",Гопаненко Владимир Владимирович,...,"0,00","0,00","0,00","0,00",NaN,NaN,NaN,NaN,NaN,NaT
228634,2024,54.28.07.028.00,Обработка почвы,Культивация,2024-10-28,2024-10-28,"6,00","Трактор колесный John Deere 9470R, гос.ном. 48...","Культиватор стерневой Vaderstad TopDown 700, и...",Гамануха Дмитрий Владимирович,...,"0,00","0,00","0,00","0,00",NaN,NaN,NaN,NaN,NaN,NaT
228635,2024,54.17.02.022.00,Уборка,Вывоз,2024-10-28,2024-10-28,"73,93","Трактор колесный Птз К-744Р1, гос.ном. 2206НМ7...",NaN,Строй Дмитрий Александрович,...,"5,69","170,67","221,63","4,81",NaN,NaN,NaN,NaN,NaN,NaT